### ISSUE TITLE
ShapeAdaptor issue

### ISSUE THREAD

**Issue by freeman-1995** [lorenmt/shape-adaptor#1]
hi, I git clone your project and run model_train.py, some problem occured

here are some errors:
Traceback (most recent call last):
  File "model_training.py", line 421, in <module>
    main()
  File "model_training.py", line 357, in main
    if ShapeAdaptor.current_dim_true < args.limit_dim:
AttributeError: 'function' object has no attribute 'current_dim_true'

ShapeAdapto is defined in model_list but It's a function not a class, pls help to check the code is right

**Comment by lorenmt** [comment]
Hi,

The code is correct.

The `ShapeAdaptor.current_dim_true` is defined in each network forward function. For example in VGG network, it's in line 174 - 176. This `current_dim_true` indicates the true output dimension dynamically updated for each iteration without the memory penalty, which is required to compute the corresponding penalty term to make it grow no more than the required `limit_dim`.

As such, this `current_dim_true` will only be available if we have at least one network pass using the forward function, i.e. running `predict = model(data)` at least once. 

If you make sure you did not modify any part of the code, just try `python model_training.py --gpu ID` to test. It should give no error.

Hope it helps.

Sk.

**Comment by lorenmt** [comment]
At the very first iteration, which `current_limit_dim` has not yet defined, python would directly give True if one of the conditions in `or` is true.

For example, if you try `True or a` even if `a` is not defined, it would output a True.

**Comment by freeman-1995** [comment]
ok, Maybe I add some bugs while modified the code to distributed training

**Comment by lorenmt** [comment]
Ok. Make sure the model has at least one pass on the training data.. Should be an easy fix.
