### ISSUE TITLE
Is it possible to train with Multi-GPUs?

### ISSUE THREAD

**Issue by KleinXin** [lorenmt/shape-adaptor#5]
I have a very large dataset which has about 4 Million images and more that 4000 classes.

Is it possible to train with Multi-GPUs?

**Comment by lorenmt** [comment]
Hello,

Yes, shape adaptor networks as similar to other standard network designs can be trained with multi-GPUs. Our ImageNet results were trained with 8 GPUs. However, considering that many number of training images, we need to re-search the hyper-parameters. You could start using hyper-parameters listed for ImageNet as a start (see Arxiv-version paper Appendix).

Sk.

**Comment by KleinXin** [comment]
> Hello,
> 
> Yes, shape adaptor networks as similar to other standard network designs can be trained with multi-GPUs. Our ImageNet results were trained with 8 GPUs. However, considering that many number of training images, we need to re-search the hyper-parameters. You could start using hyper-parameters listed for ImageNet as a start (see Arxiv-version paper Appendix).
> 
> Sk.

Could you please tell me how to set multi-gpus？The parameter gpu in model_training.py is of type int instead of array.

thx!

**Comment by lorenmt** [comment]
I would suggest following the official ImageNet training guide. https://github.com/pytorch/examples/tree/master/imagenet
