### ISSUE TITLE
GMACs for ImageNet dataset?

### ISSUE THREAD

**Issue by DongHwanJang** [lorenmt/shape-adaptor#8]
In the paper, it seems that there is no report of FLOPs for most of settings (especially for ImageNet dataset)
However, FLOPs comparison seems essential for follow-up studies.

Rather than conducting all experiments directly again, it would be greatly helpful to have a record of FLOPs.
Would there be FLOPs recorded for each setting?

**Comment by lorenmt** [comment]
In Table 5, we have provided the FLOPs computation, with bounded shapes. In Table 1, the learned shape is always having greater FLOPs, which we just try to see the upper bound of generalization if having no constraints on the network shape.
